# Web scrapping using pandas

In [3]:
import pandas as pd

In [6]:
# Reading 1 csv file from the website using pandas
df_premiere24 = pd.read_csv('https://football-data.co.uk/mmz4281/2425/E0.csv')
df_premiere24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [7]:
df_premiere24.rename(columns={"FTHG": "home_goals", "FTAG": "away_goals"}, inplace=True)

In [8]:
df_premiere24

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [9]:
link_structure = "https://football-data.co.uk/mmz4281/" + "2425" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2425/E0.csv'

In [40]:
# Creating a root variable
root = "https://football-data.co.uk/mmz4281/"

In [61]:
for season in range(21, 25):
    print(season)
    print(str(season) + str(season+  1))

21
2122
22
2223
23
2324
24
2425

In [62]:
import pandas as pd
root = "https://football-data.co.uk/mmz4281/"
leagues = ["E0", "E1", "E2", "E3", "EC"]
seasons = ["2122", "2223", "2324", "2425"]
frames = []

for league in leagues:
    for season in range(21, 25):
        season_str = str(season) + str(season + 1)
        url = f'{root}{season_str}/{league}.csv'
        print(f"Downloading {url}")

        try:
            df = pd.read_csv(url, encoding="UTF-8")
        except UnicodeDecodeError:
            try:
                df = pd.read_csv(url, encoding="ISO-8859-1")
            except Exception as e:
                print(f"Failed to decode {league} {season_str}: error: {e}")

        except Exception as e:
            print(f"Failed to load {league} {season_str}: error: {e}")
            continue
        df["League"] = league
        df["Season"] = season_str
        frames.append(df)
        print(df.head())

Downloading https://football-data.co.uk/mmz4281/2122/E0.csv
  Div        Date   Time    HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  13/08/2021  20:00   Brentford         Arsenal     2     0   H     1
1  E0  14/08/2021  12:30  Man United           Leeds     5     1   H     1
2  E0  14/08/2021  15:00     Burnley        Brighton     1     2   A     1
3  E0  14/08/2021  15:00     Chelsea  Crystal Palace     3     0   H     2
4  E0  14/08/2021  15:00     Everton     Southampton     3     1   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.75     2.05   1.81   2.13     2.05     2.17     1.80
1     0  ...     2.05     1.75   2.17   1.77     2.19     1.93     2.10
2     0  ...     1.79     2.15   1.81   2.14     1.82     2.19     1.79
3     0  ...     2.05     1.75   2.12   1.81     2.16     1.93     2.06
4     1  ...     2.05     1.88   2.05   1.88     2.08     1.90     2.03

   AvgCAHA  League  Season
0     2.09      E0    2122
1     1.79      E0    2122
2     2.12      E0    2122
3     1.82      E0    2122
4     1.86      E0    2122

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2223/E0.csv
  Div        Date   Time        HomeTeam       AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  05/08/2022  20:00  Crystal Palace        Arsenal     0     2   A     0
1  E0  06/08/2022  12:30          Fulham      Liverpool     2     2   D     1
2  E0  06/08/2022  15:00     Bournemouth    Aston Villa     2     0   H     1
3  E0  06/08/2022  15:00           Leeds         Wolves     2     1   H     1
4  E0  06/08/2022  15:00       Newcastle  Nott'm Forest     2     0   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     1  ...     2.09     1.84   2.04   1.88     2.09     1.88     2.03
1     0  ...     1.90     2.03   1.91   2.02     2.01     2.06     1.89
2     0  ...     1.93     2.00   1.93   2.00     1.94     2.04     1.88
3     1  ...     2.08     1.85   2.10   1.84     2.14     1.87     2.08
4     0  ...     1.97     1.96   1.99   1.93     2.19     1.97     2.03

   AvgCAHA  League  Season
0     1.85      E0    2223
1     1.99      E0    2223
2     2.00      E0    2223
3     1.81      E0    2223
4     1.86      E0    2223

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2324/E0.csv
  Div        Date   Time     HomeTeam       AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  11/08/2023  20:00      Burnley       Man City     0     3   A     0
1  E0  12/08/2023  12:30      Arsenal  Nott'm Forest     2     1   H     2
2  E0  12/08/2023  15:00  Bournemouth       West Ham     1     1   D     0
3  E0  12/08/2023  15:00     Brighton          Luton     4     1   H     1
4  E0  12/08/2023  15:00      Everton         Fulham     0     1   A     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     2  ...     1.95     1.98   1.95   1.97      NaN      NaN     1.92
1     0  ...     1.95     1.98   1.93   1.97     2.01     2.09     1.95
2     0  ...     2.02     1.91   2.01   1.92     2.06     1.96     1.96
3     0  ...     2.01     1.92   2.00   1.91     2.14     1.93     2.00
4     0  ...     2.06     1.87   2.04   1.88     2.08     1.99     1.98

   AvgCAHA  League  Season
0     1.95      E0    2324
1     1.92      E0    2324
2     1.91      E0    2324
3     1.86      E0    2324
4     1.88      E0    2324

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2425/E0.csv
  Div        Date   Time    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
0  E0  16/08/2024  20:00  Man United       Fulham     1     0   H     0     0
1  E0  17/08/2024  12:30     Ipswich    Liverpool     0     2   A     0     0
2  E0  17/08/2024  15:00     Arsenal       Wolves     2     0   H     1     0
3  E0  17/08/2024  15:00     Everton     Brighton     0     3   A     0     1
4  E0  17/08/2024  15:00   Newcastle  Southampton     1     0   H     1     0

   ... PCAHH PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  BFECAHA  \
0  ...  1.83  2.11     1.88     2.11     1.82     2.05     1.90     2.08
1  ...  2.04  1.90     2.20     2.00     1.99     1.88     2.04     1.93
2  ...  2.00  1.90     2.05     1.93     1.99     1.87     2.02     1.96
3  ...  1.86  2.07     1.92     2.10     1.83     2.04     1.88     2.11
4  ...  1.88  2.06     1.89     2.10     1.82     2.05     1.89     2.10

   League  Season
0      E0    2425
1      E0    2425
2      E0    2425
3      E0    2425
4      E0    2425

[5 rows x 122 columns]
Downloading https://football-data.co.uk/mmz4281/2122/E1.csv
  Div        Date   Time      HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E1  06/08/2021  19:45   Bournemouth     West Brom     2     2   D     1
1  E1  07/08/2021  15:00     Blackburn       Swansea     2     1   H     1
2  E1  07/08/2021  15:00  Bristol City     Blackpool     1     1   D     1
3  E1  07/08/2021  15:00       Cardiff      Barnsley     1     1   D     0
4  E1  07/08/2021  15:00         Derby  Huddersfield     1     1   D     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     1  ...     2.13     1.78   2.13   1.80     2.16     1.83     2.09
1     0  ...     1.77     2.14   1.83   2.09     1.87     2.17     1.81
2     0  ...     1.90     2.00   1.92   1.99     1.92     2.01     1.89
3     0  ...     2.05     1.75   2.14   1.80     2.19     1.80     2.11
4     1  ...     1.88     2.02   1.88   2.01     1.90     2.07     1.87

   AvgCAHA  League  Season
0     1.77      E1    2122
1     2.04      E1    2122
2     1.95      E1    2122
3     1.75      E1    2122
4     1.98      E1    2122

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2223/E1.csv
  Div        Date   Time      HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E1  29/07/2022  20:00  Huddersfield       Burnley     0     1   A     0
1  E1  30/07/2022  15:00     Blackburn           QPR     1     0   H     1
2  E1  30/07/2022  15:00     Blackpool       Reading     1     0   H     1
3  E1  30/07/2022  15:00       Cardiff       Norwich     1     0   H     0
4  E1  30/07/2022  15:00          Hull  Bristol City     2     1   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     1  ...     2.09     1.81   2.10   1.82     2.14     1.83     2.09
1     0  ...     1.99     1.91   2.01   1.90     2.01     1.95     1.97
2     0  ...     2.08     1.82   2.06   1.86     2.11     1.86     2.04
3     0  ...     2.01     1.89   2.00   1.90     2.03     2.00     1.95
4     1  ...     2.10     1.70   2.12   1.81     2.17     1.81     2.09

   AvgCAHA  League  Season
0     1.78      E1    2223
1     1.88      E1    2223
2     1.82      E1    2223
3     1.89      E1    2223
4     1.77      E1    2223

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2324/E1.csv
  Div        Date   Time        HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E1  04/08/2023  20:00  Sheffield Weds  Southampton     1     2   A     0
1  E1  05/08/2023  15:00       Blackburn    West Brom     2     1   H     2
2  E1  05/08/2023  15:00    Bristol City      Preston     1     1   D     0
3  E1  05/08/2023  15:00   Middlesbrough     Millwall     0     1   A     0
4  E1  05/08/2023  15:00         Norwich         Hull     2     1   H     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     1  ...     1.91     1.99   1.93   2.00     1.97     2.00     1.88
1     0  ...     2.05     1.85   2.07   1.85     2.10     1.88     2.03
2     0  ...     1.82     2.08   1.84   2.08     1.88     2.15     1.80
3     0  ...     1.80     2.10   1.83   2.10     1.91     2.14     1.85
4     1  ...     2.06     1.84   2.05   1.86     2.10     1.91     2.01

   AvgCAHA  League  Season
0     1.95      E1    2324
1     1.82      E1    2324
2     2.04      E1    2324
3     1.99      E1    2324
4     1.83      E1    2324

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2425/E1.csv
  Div        Date   Time   HomeTeam          AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E1  09/08/2024  20:00  Blackburn             Derby     4     2   H     1
1  E1  09/08/2024  20:00    Preston  Sheffield United     0     2   A     0
2  E1  10/08/2024  12:30    Cardiff        Sunderland     0     2   A     0
3  E1  10/08/2024  12:30       Hull      Bristol City     1     1   D     0
4  E1  10/08/2024  12:30      Leeds        Portsmouth     3     3   D     1

   HTAG  ... PCAHH PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  \
0     0  ...  1.85  2.06     1.97     2.10     1.85     1.99     1.88
1     1  ...  1.93  1.98     1.97     1.99     1.90     1.94     1.94
2     1  ...  2.13  1.80     2.13     1.81     2.09     1.79     2.18
3     0  ...  2.00  1.91     2.04     1.91     1.99     1.87     2.03
4     2  ...  1.93  1.95     2.00     1.98     1.94     1.89     2.00

   BFECAHA  League  Season
0     2.11      E1    2425
1     2.04      E1    2425
2     1.83      E1    2425
3     1.96      E1    2425
4     1.97      E1    2425

[5 rows x 122 columns]
Downloading https://football-data.co.uk/mmz4281/2122/E2.csv
  Div        Date   Time        HomeTeam            AwayTeam  FTHG  FTAG FTR  \
0  E2  07/08/2021  15:00          Bolton  Milton Keynes Dons     3     3   D
1  E2  07/08/2021  15:00       Cambridge              Oxford     1     1   D
2  E2  07/08/2021  15:00           Crewe          Cheltenham     1     1   D
3  E2  07/08/2021  15:00       Doncaster       AFC Wimbledon     1     2   A
4  E2  07/08/2021  15:00  Fleetwood Town          Portsmouth     0     1   A

   HTHG  HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     1     1  ...     1.90     1.95   1.91   1.97     1.99     2.01     1.90
1     0     1  ...     2.08     1.73   2.12   1.78     2.12     1.82     2.06
2     1     1  ...     2.00     1.85   1.99   1.90     2.04     1.95     1.96
3     0     0  ...     2.10     1.77   2.11   1.80     2.12     1.82     2.07
4     0     0  ...     2.05     1.80   2.09   1.82     2.13     1.86     2.07

   AvgCAHA  League  Season
0     1.92      E2    2122
1     1.77      E2    2122
2     1.87      E2    2122
3     1.77      E2    2122
4     1.78      E2    2122

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2223/E2.csv
  Div        Date   Time     HomeTeam            AwayTeam  FTHG  FTAG FTR  \
0  E2  30/07/2022  15:00   Accrington            Charlton     2     2   D
1  E2  30/07/2022  15:00  Bristol Rvs        Forest Green     1     2   A
2  E2  30/07/2022  15:00    Cambridge  Milton Keynes Dons     1     0   H
3  E2  30/07/2022  15:00   Cheltenham           Peterboro     2     3   A
4  E2  30/07/2022  15:00        Derby              Oxford     1     0   H

   HTHG  HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0     1  ...     2.05     1.75   2.08   1.83     2.16     1.83     2.06
1     0     0  ...     2.10     1.77   2.09   1.82     2.13     1.82     2.07
2     1     0  ...     1.70     2.10   1.76   2.14     1.86     2.14     1.78
3     2     0  ...     1.93     1.93   1.98   1.90     1.98     1.99     1.89
4     0     0  ...     1.75     2.05   1.79   2.10     1.86     2.14     1.79

   AvgCAHA  League  Season
0     1.77      E2    2223
1     1.76      E2    2223
2     2.05      E2    2223
3     1.92      E2    2223
4     2.03      E2    2223

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2324/E2.csv
  Div        Date   Time   HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E2  05/08/2023  15:00   Barnsley       Port Vale     7     0   H     2
1  E2  05/08/2023  15:00  Blackpool          Burton     2     0   H     2
2  E2  05/08/2023  15:00     Bolton         Lincoln     3     0   H     1
3  E2  05/08/2023  15:00  Cambridge          Oxford     2     0   H     2
4  E2  05/08/2023  15:00   Carlisle  Fleetwood Town     1     1   D     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     2.03     1.83   2.07   1.83     2.09     1.85     2.01
1     0  ...     1.93     1.93   1.94   1.94     1.96     1.97     1.88
2     0  ...     2.00     1.85   2.01   1.88     2.02     1.92     1.96
3     0  ...     1.93     1.93   1.95   1.93     2.00     1.98     1.90
4     1  ...     2.00     1.85   2.07   1.83     2.08     1.90     2.00

   AvgCAHA  League  Season
0     1.80      E2    2324
1     1.91      E2    2324
2     1.84      E2    2324
3     1.90      E2    2324
4     1.80      E2    2324

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2425/E2.csv
  Div        Date   Time      HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E2  09/08/2024  20:00      Barnsley    Mansfield     1     2   A     1
1  E2  10/08/2024  17:30    Birmingham      Reading     1     1   D     0
2  E2  10/08/2024  17:30   Bristol Rvs  Northampton     1     0   H     0
3  E2  10/08/2024  17:30        Burton      Lincoln     2     3   A     2
4  E2  10/08/2024  17:30  Crawley Town    Blackpool     2     1   H     2

   HTAG  ... PCAHH PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  \
0     2  ...  2.02  1.87     2.05     2.00     1.95     1.85     2.06
1     1  ...  1.81  2.10     1.83     2.10     1.80     2.01     1.82
2     0  ...  1.98  1.91     1.98     1.92     1.93     1.86     2.02
3     2  ...  1.82  2.08     1.88     2.09     1.80     2.01     1.88
4     0  ...  1.85  2.04     1.86     2.05     1.82     1.99     1.89

   BFECAHA  League  Season
0     1.93      E2    2425
1     2.16      E2    2425
2     1.97      E2    2425
3     2.11      E2    2425
4     2.08      E2    2425

[5 rows x 122 columns]
Downloading https://football-data.co.uk/mmz4281/2122/E3.csv
  Div        Date   Time      HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E3  07/08/2021  15:00      Carlisle    Colchester     0     0   D     0
1  E3  07/08/2021  15:00        Exeter      Bradford     0     0   D     0
2  E3  07/08/2021  15:00  Forest Green        Sutton     2     1   H     1
3  E3  07/08/2021  15:00     Harrogate      Rochdale     3     2   H     2
4  E3  07/08/2021  15:00    Hartlepool  Crawley Town     1     0   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.75     2.05   1.78   2.13     1.82     2.13     1.75
1     0  ...     1.80     2.05   1.79   2.12     1.87     2.12     1.80
2     0  ...     1.98     1.83   1.93   1.95     2.03     1.99     1.91
3     1  ...     1.90     1.95   1.90   1.98     1.94     1.98     1.88
4     0  ...     1.90     1.95   1.93   1.95     1.96     1.98     1.90

   AvgCAHA  League  Season
0     2.08      E3    2122
1     2.03      E3    2122
2     1.90      E3    2122
3     1.94      E3    2122
4     1.91      E3    2122

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2223/E3.csv
  Div        Date   Time       HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E3  30/07/2022  15:00  AFC Wimbledon    Gillingham     2     0   H     1
1  E3  30/07/2022  15:00       Bradford     Doncaster     0     0   D     0
2  E3  30/07/2022  15:00       Carlisle  Crawley Town     1     0   H     1
3  E3  30/07/2022  15:00      Harrogate       Swindon     3     0   H     1
4  E3  30/07/2022  15:00  Leyton Orient       Grimsby     2     0   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     2.05     1.80   2.09   1.81     2.13     1.81     2.06
1     0  ...     1.90     1.95   1.90   1.99     1.96     1.99     1.90
2     0  ...     1.80     2.05   1.88   2.02     1.88     2.11     1.79
3     0  ...     1.77     2.10   1.77   2.14     1.84     2.14     1.76
4     0  ...     1.80     2.05   1.79   2.10     1.86     2.10     1.80

   AvgCAHA  League  Season
0     1.76      E3    2223
1     1.91      E3    2223
2     2.03      E3    2223
3     2.06      E3    2223
4     2.02      E3    2223

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2324/E3.csv
  Div        Date   Time      HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E3  05/08/2023  15:00    Accrington  Newport County     3     0   H     1
1  E3  05/08/2023  15:00  Crawley Town        Bradford     1     0   H     1
2  E3  05/08/2023  15:00         Crewe       Mansfield     2     2   D     1
3  E3  05/08/2023  15:00     Doncaster       Harrogate     0     1   A     0
4  E3  05/08/2023  15:00  Forest Green         Salford     0     2   A     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     2.00     1.80   2.07   1.83     2.12     1.83     2.05
1     0  ...     1.90     1.95   1.91   1.98     1.94     1.99     1.86
2     2  ...     2.00     1.85   2.01   1.88     2.06     1.89     1.96
3     0  ...     2.03     1.83   2.05   1.85     2.08     1.88     1.99
4     0  ...     1.80     2.05   1.85   2.04     1.85     2.11     1.78

   AvgCAHA  League  Season
0     1.75      E3    2324
1     1.92      E3    2324
2     1.82      E3    2324
3     1.80      E3    2324
4     2.00      E3    2324

[5 rows x 108 columns]
Downloading https://football-data.co.uk/mmz4281/2425/E3.csv
  Div        Date   Time       HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E3  09/08/2024  20:00   Chesterfield         Swindon     1     1   D     1
1  E3  10/08/2024  15:00  AFC Wimbledon      Colchester     4     2   H     3
2  E3  10/08/2024  15:00         Barrow           Crewe     1     0   H     1
3  E3  10/08/2024  15:00     Cheltenham  Newport County     3     2   H     2
4  E3  10/08/2024  15:00      Doncaster      Accrington     4     1   H     1

   HTAG  ... PCAHH PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  BFECAHH  \
0     0  ...  1.86  2.03     1.89     2.05     1.83     1.97     1.91
1     2  ...  1.83  2.07     1.83     2.17     1.76     2.05     1.86
2     0  ...  1.87  2.02     1.90     2.04     1.84     1.95     1.88
3     2  ...  1.96  1.93     1.98     1.96     1.91     1.88     2.05
4     0  ...  1.95  1.93     1.95     1.98     1.89     1.89     1.98

   BFECAHA  League  Season
0     2.06      E3    2425
1     2.12      E3    2425
2     2.09      E3    2425
3     1.92      E3    2425
4     2.00      E3    2425

[5 rows x 122 columns]
Downloading https://football-data.co.uk/mmz4281/2122/EC.csv
  Div        Date   Time     HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  EC  21/08/2021  15:00    Aldershot  Chesterfield     0     2   A     0
1  EC  21/08/2021  15:00       Barnet  Notts County     0     5   A     0
2  EC  21/08/2021  15:00      Halifax    Maidenhead     1     2   A     1
3  EC  21/08/2021  15:00  Kings Lynn      Southend     0     1   A     0
4  EC  21/08/2021  15:00     Solihull       Wrexham     2     2   D     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.98     1.83   2.03   1.83     2.05     1.90     1.97
1     0  ...     1.88     1.93   1.90   1.95     2.00     1.95     1.90
2     0  ...     1.93     1.88   1.99   1.87     2.03     1.93     1.94
3     1  ...     1.75     2.05   1.81   2.06     1.90     2.11     1.76
4     2  ...     2.05     1.75   1.93   1.92     2.05     1.98     1.92

   AvgCAHA  League  Season
0     1.80      EC    2122
1     1.88      EC    2122
2     1.84      EC    2122
3     2.02      EC    2122
4     1.86      EC    2122

[5 rows x 100 columns]
Downloading https://football-data.co.uk/mmz4281/2223/EC.csv
  Div        Date   Time     HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
0  EC  06/08/2022  15:00    Aldershot      Solihull     1     4   A     1
1  EC  06/08/2022  15:00   Altrincham     Maidstone     1     1   D     1
2  EC  06/08/2022  15:00       Barnet       Halifax     2     0   H     1
3  EC  06/08/2022  15:00  Dag and Red     Gateshead     2     2   D     1
4  EC  06/08/2022  15:00      Dorking  Chesterfield     2     2   D     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \

In [59]:
len(frames)
first_match = frames[0]
first_match

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,League,Season
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09,E0,2122
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79,E0,2122
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12,E0,2122
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82,E0,2122
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86,E0,2122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16,E0,2122
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01,E0,2122
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80,E0,2122
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87,E0,2122
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89,E0,2122